name: Python CI

# Trigger the workflow on any push/pull to main branch
on:
  push:
    branches: 
      - main
  pull_request: 
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - checkout the code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 - setup python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3 - install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
          pip install pytest

      # Step 4 - run the tests
      - name: Run tests
        run: pytest
